config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'tops#index'

  resources :users, only: [:new, :create]
  resource :user_session, only: [:new, :create, :destroy]

  resources :test_results do
    collection do
      get 'my_results'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/test_result.rb
class TestResult < ApplicationRecord
  belongs_to :user

  validates :test_name, presence: true, length: { maximum: 255 }
  validates :score, presence: true, numericality: { less_than_or_equal_to: :max_score } 
  validates :max_score, presence: true, numericality: { greater_than_or_equal_to: 0 } 
  
  before_save :calculate_achievement_rate

  private

  def calculate_achievement_rate
    return if score.nil? || max_score.nil?
    self.achievement_rate = ((score.to_f / max_score) * 100).round
  end

  def self.user_test_results(user)
    where(user: user).pluck(:test_name, :achievement_rate)
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :test_results, dependent: :destroy

  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :nickname, presence: true
  validates :email, uniqueness: true, presence: true
  validates :grade_and_class, presence: true
  
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  def own?(object)
    id == object.user_id
  end

  def average_achievement_rate
    test_results.average(:achievement_rate)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
end

app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  before_action :find_test_result, only: [:edit, :update, :destroy]

  def index
    @test_results = TestResult.all
  end

  def new
    @test_result = TestResult.new
  end

  def create
    @test_result = current_user.test_results.build(test_result_params)
    if @test_result.save
      redirect_to test_results_path, success: t('defaults.message.created', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: TestResult.model_name.human)
      render :new
    end
  end

  def show
    @test_result = TestResult.find(params[:id])
  end

  def edit; end

  def update
    if @test_result.update(test_result_params)
      redirect_to @test_result, success: t('defaults.message.updated', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: TestResult.model_name.human)
      render :edit
    end
  end

  def destroy
    @test_result.destroy!
    redirect_to test_results_path, success: t('defaults.message.deleted', item: TestResult.model_name.human)
  end

  def my_results
    # ログインユーザーだけのテスト結果を取得
    @my_test_results = current_user.test_results.order(created_at: :desc).page(params[:page])
  end

  private

  def find_test_result
    @test_result = current_user.test_results.find(params[:id])
  end

  def test_result_params
    params.require(:test_result).permit(:test_name, :score, :max_score)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, notice: 'Logged in!'
    else
      flash.now[:alert] = 'Login failed!'
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to new_user_session_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created successfully"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :last_name, :first_name, :nickname, :grade_and_class)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def grade_and_class_options
    grades = ['1年', '2年', '3年']
    classes = (1..10).to_a.map { |n| "#{n}組" }
                    
    grades.product(classes).map { |grade, klass| ["#{grade.strip} #{klass.strip}", "#{grade.strip} #{klass.strip}"] }
  end
end

app/helpers/test_results_helper.rb
module TestResultsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Score</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="page-wrapper">
      <% if logged_in? %>
        <%= render 'shared/header' %>
      <% else %>
        <%= render 'shared/before_login_header' %>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
  <div class="container px-0">
    <a href="index.html" class="navbar-brand pe-3">
      <%= link_to root_path, class: "navbar-brand pe-3" do %>
      TestScoreRivels
      <% end %>
    </a>
    <div id="navbarNav" class="offcanvas offcanvas-end">
      <div class="offcanvas-header border-top">
        <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex' %>
      </div>      
    </div>
    <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex' %>
  </div>
</header>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="footer border-top pt-5 pb-4 pb-lg-5">
  <div class="container text-center pt-2 pt-md-4 pt-lg-5 pb-xl-3">
    <div class="pt-5 mt-lg-3 mt-xl-4">
      <p class="text-muted mb-0">&copy; All rights reserved. TestScoreRivels</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- Navbar -->
<!-- Remove "fixed-top" class to make navigation bar scrollable with the page -->
<header class="header navbar navbar-expand-lg bg-light shadow-sm fixed-top">
  <div class="container px-0">
    <a href="index.html" class="navbar-brand pe-3">
      <%= link_to root_path, class: "navbar-brand pe-3" do %>
      TestScoreRivels
      <% end %>
    </a>
    <div id="navbarNav" class="offcanvas offcanvas-end">
      <div class="offcanvas-header border-top">
        <%= link_to 'ログアウト', user_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
      </div>      
    </div>
    <%= link_to 'ログアウト', user_session_path, class: 'btn btn-primary btn-sm fs-sm rounded d-none d-lg-inline-flex', data: {turbo_method: :delete} %>
  </div>
</header>

app/views/test_results/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <% if current_user && current_user == test_result.user %>
    <li class="list-inline-item">
      <%= link_to edit_test_result_path(test_result), id: "button-edit-#{test_result.id}" do %>
        <%= icon 'fa', 'pen' %>
      <% end %>
    </li>
    <li class="list-inline-item">
      <%= link_to test_result_path(test_result), id: "button-delete-#{test_result.id}", method: :delete, data: { confirm: t('defaults.message.delete_confirm') } do %>
        <%= icon 'fas', 'trash' %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/test_results/index.html.erb
<!-- Breadcrumb -->
<nav class="container mt-lg-4 pt-5" aria-label="breadcrumb"></nav>
<!-- Page content -->
<section class="container mt-4 mb-lg-5 pt-lg-2 pb-5">
  <!-- Page title + Layout switcher + Search form -->
  <div class="row align-items-end gy-3 mb-4 pb-lg-3 pb-1">
    <div class="col-lg-5 col-md-4">
      <h1 class="mb-2 mb-md-0"><%= t '.title' %></h1>
    </div>
  </div>
  <!-- Blog grid -->
  <div class="row row-cols-lg-3 row-cols-sm-2 row-cols-1 gy-md-4 gy-2">
    <% @test_results.each do |test_result| %>
      <!-- Item -->
      <div class="col pb-3">
        <article class="card border-0 shadow-sm h-100">
          <div class="card-body pb-4">
            <div class="d-flex align-items-center justify-content-between mb-3">
              <%= render 'crud_menus', test_result: test_result if current_user.own?(test_result) %>
              <li class="list-inline-item">
                <%= icon 'far', 'calendar' %>
                <%= l test_result.created_at, format: :long %>
              </li>
            </div>
            <h3 class="h5 mb-3">
              <%= link_to test_result.test_name, test_result_path(test_result) %>
            </h3>
            <p class="h5 mb-3">
              <p><strong>点数</strong><span class="fs-lg fw-semibold text-danger me-2"> <%= test_result.score %></span></p>
              <p><strong>満点</strong><span class="fs-lg fw-semibold text-danger me-2"> <%= test_result.max_score %></span></p>
              <p><strong>達成率</strong><span class="fs-lg fw-semibold text-danger me-2"> <%= test_result.achievement_rate %>%</span></p>
          </div>
          <div class="card-footer py-4">
            <%= image_tag 'sample', size: '40x40', class: 'rounded-circle mr15'%>
            <%= link_to test_result.user.decorate.full_name, users_path(test_result.user) %>
          </div>
        </article>
      </div>
      <% end %>
   </div>
</section>

app/views/test_results/new.html.erb
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><%= t '.title' %></h1>
    <%= form_with model: @test_result, local: true do |f| %>
      <div class="row">
        <div class="col-12 mb-4">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :test_name %>
              <%= f.text_field :test_name, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :max_score %>
              <%= f.number_field :max_score, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :score %>
              <%= f.number_field :score, class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit '登録する', class: "btn btn-primary shadow-primary btn-lg w-100" %>
    <% end %>
  </div>
</div>

app/views/tops/index.html.erb
<div class="container pt-3">
  <div class="row">
    <h1 class="mb-4"><%= t '.title' %></h1>
  </div>
</div>

app/views/user_sessions/new.html.erb
<!-- Sign in form -->
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><%= t '.title' %></h1>
    <p class="text-center text-xl-start pb-3 mb-3">新規登録はお済みですか? <%= link_to "新規登録画面へ", new_user_path %></p>
    <%= form_with url: user_session_path, local: true do |f| %>
      <div class="position-relative mb-4">
        <div class="form-group">
          <%= f.label :email, User.human_attribute_name(:email) %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
      </div>
      <div class="mb-4">
        <div class="form-group">
          <%= f.label :password, User.human_attribute_name(:password)  %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
      </div>
      <div class="actions">
        <%= f.submit (t 'defaults.login'), class: 'btn btn-primary shadow-primary btn-lg w-100' %>
      </div>
    <% end %>
    <a href="#" class="btn btn-link btn-lg w-100">パスワードをお忘れですか?</a>
  </div>
</div>

app/views/users/new.html.erb
<!-- Sign up form -->
<div class="container d-flex flex-wrap justify-content-center justify-content-center pt-5">
  <div class="w-100 align-self-end pt-1 pt-md-4 pb-4" style="max-width: 526px;">
    <h1 class="text-center text-xl-start"><%= t '.title' %></h1>
    <p class="text-center text-xl-start pb-3 mb-3">すでにアカウントを持っていますか? <%= link_to "ログインはこちら", new_user_session_path %></p>
    <%= form_with model: @user, local: true do |f| %>
      <div class="row">
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :first_name %>
              <%= f.text_field :first_name, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :nickname %>
              <%= f.text_field :nickname, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12 mb-4">
          <div class="position-relative mb-4">
            <div class="form-group">
              <%= f.label :grade_and_class %>
              <%= f.select :grade_and_class, options_for_select(grade_and_class_options), {}, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="col-12 mb-4">
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
        </div>
        <div class="col-12 mb-4">
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>
      </div>
      <%= f.submit '新規登録', class: "btn btn-primary shadow-primary btn-lg w-100" %>
    <% end %>
  </div>
</div>